[package]
name = "codestory-events"
version = "0.1.0"
edition = "2021"

[dependencies]
codestory-core = { workspace = true }
crossbeam-channel = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
egui = { workspace = true }
